HW6/HW6/Controllers/HomeController.cs
using HW6.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HW6.Views
{
    public class HomeController : Controller
    {
        private AdvWorksContext db = new AdvWorksContext();
        // GET: Home
        /// <summary>
        /// Displays the Main categories sorted descending by name.
        /// </summary>
        public ActionResult Index()
        {
            var products = db.ProductCategories.OrderByDescending(p => p.Name).ToList();
            return View(products);
        }

        /// <summary>
        /// Displays the subcategories based off the ID of the parent category.
        /// </summary>
        /// <param name="ID">Category ID</param>
        public ActionResult CategoryResults(int? ID)
        {
            if (ID == null) { ID = 1; }
            var products = db.ProductSubcategories.Where(n => n.ProductCategoryID == ID).OrderByDescending(p => p.Name);
            return View(products);
        }

        /// <summary>
        /// Lists of products in the subcategory
        /// </summary>
        /// <param name="ID">Subcategory ID</param>
        public ActionResult ProductList(int? ID)
        {
            if (ID == null) { ID = 1; }
            var products = db.Products.Where(n => n.ProductSubcategoryID == ID).OrderByDescending(p => p.Name);
            return View(products);
        }

        /// <summary>
        /// Displays the details of a product.
        /// </summary>
        /// <param name="ID">Product ID</param>
        public ActionResult ProductDetails(string ID)
        {
            var product = db.Products.Where(n => n.ProductNumber == ID).First();
            return View(product);
        }
        

        //Get
        /// <summary>
        /// Returns a specific product review.
        /// </summary>
        /// <param name="ID">Review ID</param>
        public ActionResult Reviews(int ID)
        {
            if (ID == null) { ID = 709; }
            var product = db.Products.Where(n => n.ProductID == ID).First();
            return View(product.ProductReviews);
        }

        //Not Used at this time...
        //Get
        [HttpGet]
        public ActionResult NewReview(int? ID)
        {

            if (ID == null) { ID = 1; }
            ViewBag.id = (int)ID;
            return View();
        }

        //Not used at this time
        //Post
        [HttpPost]
        public ActionResult NewReview([Bind(Include = "ProductID,ReviewerName,ReviewDate,EmailAddress,Rating,Comments,ModefiedDate")] ProductReview review)
        {
            if (ModelState.IsValid)
            {
                db.ProductReviews.Add(review);
                db.SaveChanges();
                return RedirectToAction("Reviews/"+ review.ProductID);
            }

            return View(review.ProductID);
        }
    }
}

HW6/HW6/Controllers/ProductReviewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace HW6.Models
{
    public class ProductReviewsController : Controller
    {
        private AdvWorksContext db = new AdvWorksContext();

        // GET: ProductReviews
        public ActionResult Index()
        {
            var productReviews = db.ProductReviews.Include(p => p.Product);
            return View(productReviews.ToList());
        }

        public ActionResult ReviewList(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var productReviews = db.ProductReviews.Where(p => p.ProductID == id).ToList();
            return View(productReviews);
        }

        // GET: ProductReviews/Details/5
        /// <summary>
        /// Takes an ID for a product review and returns the review.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductReview productReview = db.ProductReviews.Find(id);
            if (productReview == null)
            {
                return HttpNotFound();
            }
            return View(productReview);
        }

        // GET: ProductReviews/Create
        public ActionResult Create()
        {
            ViewBag.ProductID = new SelectList(db.Products, "ProductID", "Name");
            return View();
        }

        // POST: ProductReviews/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductReviewID,ProductID,ReviewerName,ReviewDate,EmailAddress,Rating,Comments,ModifiedDate")] ProductReview productReview)
        {
            if (ModelState.IsValid)
            {
                db.ProductReviews.Add(productReview);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProductID = new SelectList(db.Products, "ProductID", "Name", productReview.ProductID);
            return View(productReview);
        }

        // GET: ProductReviews/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductReview productReview = db.ProductReviews.Find(id);
            if (productReview == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProductID = new SelectList(db.Products, "ProductID", "Name", productReview.ProductID);
            return View(productReview);
        }

        // POST: ProductReviews/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductReviewID,ProductID,ReviewerName,ReviewDate,EmailAddress,Rating,Comments,ModifiedDate")] ProductReview productReview)
        {
            if (ModelState.IsValid)
            {
                db.Entry(productReview).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProductID = new SelectList(db.Products, "ProductID", "Name", productReview.ProductID);
            return View(productReview);
        }

        // GET: ProductReviews/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductReview productReview = db.ProductReviews.Find(id);
            if (productReview == null)
            {
                return HttpNotFound();
            }
            return View(productReview);
        }

        // POST: ProductReviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProductReview productReview = db.ProductReviews.Find(id);
            db.ProductReviews.Remove(productReview);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HW6/HW6/Views/Home/CategoryResults.cshtml
@model IEnumerable<HW6.Models.ProductSubcategory>

@{
    ViewBag.Title = "CategoryResults";
}

<h2>SubCategories</h2>
<p>
    @Html.ActionLink("Back to Home", "Index")
</p>
<table class="table">
    <tr>
        <th>
            Product Category
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
           @Html.ActionLink(item.Name, "ProductList", new { ID = item.ProductSubcategoryID })
        </td>
    </tr>
}

</table>

HW6/HW6/Views/Home/Index.cshtml
@model IEnumerable<HW6.Models.ProductCategory>

@{
    ViewBag.Title = "Index";
}

<h2>Categories</h2>


<table class="table">
    <tr>
        <th>
            Main Product Categories
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.Name, "CategoryResults", new { ID = item.ProductCategoryID })
        </td>
    </tr>
}

</table>

HW6/HW6/Views/Home/NewReview.cshtml
@model HW6.Models.ProductReview

@{
    ViewBag.Title = "NewReview";
}

<h2>NewReview</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProductReview</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProductID, "ProductID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReviewerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReviewerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReviewerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReviewDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReviewDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReviewDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HW6/HW6/Views/Home/ProductDetails.cshtml
@model HW6.Models.Product

@{
    ViewBag.Title = "ProductDetails";
}

<h2>ProductDetails</h2>
<p>
    @Html.ActionLink("Back to Home", "Index")
</p>
<div>
    <h4>@Html.DisplayFor(model => model.Name)</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ListPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ListPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Size)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Size)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

    </dl>
    <p>@Html.ActionLink("See Reviews", "ReviewList", "ProductReviews", new { ID = Model.ProductID}, null) </p>
    <p>
        @Html.ActionLink("Submit New Review","Create", "ProductReviews")
    </p>
</div>

HW6/HW6/Views/Home/ProductList.cshtml
@model IEnumerable<HW6.Models.Product>

@{
    ViewBag.Title = "ProductList";
}

<h2>ProductList</h2>
<p>
    @Html.ActionLink("Back to Home", "Index")
</p>

<table class="table">
    <tr>
        <th>
            Product Name
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ListPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Size)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Weight)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.Name, "ProductDetails", new { ID = item.ProductNumber})
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ListPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Size)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Weight)
        </td>
        <td>
            
        </td>
    </tr>
}

</table>

HW6/HW6/Views/Home/Reviews.cshtml
@model IEnumerable<HW6.Models.ProductReview>

@{
    ViewBag.Title = "Reviews";
}

<h2>Reviews</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Product.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReviewerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReviewDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rating)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comments)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Product.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReviewerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReviewDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmailAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rating)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Comments)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ModifiedDate)
        </td>
    </tr>
}

</table>